package app.forma.presentation.onboarding

import app.forma.core.domain.OnboardingAnswers
import app.forma.core.model.ExperienceLevel
import app.forma.core.model.Goal
import app.forma.presentation.AppServices
import app.forma.presentation.Destination
import app.forma.presentation.PlanMapper
import app.forma.presentation.PlanUi
import app.forma.presentation.StateHolder
import app.forma.presentation.Tab
import app.forma.presentation.equipment.EquipmentDraft
import kotlinx.coroutines.CoroutineScope

enum class OnboardingStep(val title: String) {
    WELCOME("Welcome"),
    NAME("Your name"),
    GOAL("Your goal"),
    EXPERIENCE("Experience"),
    EQUIPMENT("Equipment"),
    TIME("Time"),
    SCHEDULE("Schedule"),
    CONSTRAINTS("Your space"),
    SAFETY("Before you start"),
    PREVIEW("Your first workout"),
}

data class OnboardingUiState(
    val step: OnboardingStep = OnboardingStep.WELCOME,
    val name: String = "",
    val goal: Goal? = null,
    val experience: ExperienceLevel? = null,
    val equipment: EquipmentDraft = EquipmentDraft(),
    val minutes: Int = 25,
    val days: Set<Int> = setOf(1, 3, 5),
    val quiet: Boolean = false,
    val limitedSpace: Boolean = false,
    val preview: PlanUi? = null,
    val previewError: String? = null,
    val finishing: Boolean = false,
) {
    /** Progress through the question steps (welcome and preview excluded). */
    val questionIndex: Int get() = step.ordinal
    val questionCount: Int get() = OnboardingStep.entries.size - 1

    val equipmentErrors: List<String> get() = equipment.errors()

    val canContinue: Boolean
        get() = when (step) {
            OnboardingStep.GOAL -> goal != null
            OnboardingStep.EXPERIENCE -> experience != null
            OnboardingStep.EQUIPMENT -> equipmentErrors.isEmpty()
            OnboardingStep.SCHEDULE -> days.isNotEmpty()
            OnboardingStep.PREVIEW -> preview != null && !finishing
            else -> true
        }

    val suggestedDays: Set<Int> get() = suggestDays(days.size)

    companion object {
        val MinuteOptions = listOf(10, 15, 20, 25, 30, 45)

        /** Spreads sessions across the week with rest days between them where possible. */
        fun suggestDays(count: Int): Set<Int> = when (count) {
            1 -> setOf(3)
            2 -> setOf(2, 5)
            3 -> setOf(1, 3, 5)
            4 -> setOf(1, 2, 4, 6)
            5 -> setOf(1, 2, 3, 5, 6)
            6 -> setOf(1, 2, 3, 4, 5, 6)
            else -> (1..7).toSet()
        }
    }
}

/**
 * Short, skippable onboarding with no account. Ends with a real preview of the first workout,
 * generated by the same engine as Today.
 */
class OnboardingStateHolder(scope: CoroutineScope, private val services: AppServices) :
    StateHolder<OnboardingUiState>(scope, OnboardingUiState()) {

    fun next() {
        val s = current
        if (!s.canContinue) return
        val nextStep = OnboardingStep.entries.getOrNull(s.step.ordinal + 1) ?: return
        update { it.copy(step = nextStep) }
        if (nextStep == OnboardingStep.PREVIEW) buildPreview()
    }

    fun back() {
        val previous = OnboardingStep.entries.getOrNull(current.step.ordinal - 1) ?: return
        update { it.copy(step = previous) }
    }

    /** Back is handled by the screen while there is a previous step. */
    val canGoBack: Boolean get() = current.step.ordinal > 0

    fun setName(name: String) = update { it.copy(name = name.take(40)) }
    fun setGoal(goal: Goal) = update { it.copy(goal = goal) }
    fun setExperience(level: ExperienceLevel) = update { it.copy(experience = level) }
    fun setEquipment(draft: EquipmentDraft) = update { it.copy(equipment = draft) }
    fun setMinutes(minutes: Int) = update { it.copy(minutes = minutes) }
    fun setQuiet(quiet: Boolean) = update { it.copy(quiet = quiet) }
    fun setLimitedSpace(limited: Boolean) = update { it.copy(limitedSpace = limited) }

    fun toggleDay(day: Int) = update { s ->
        val days = if (day in s.days) s.days - day else s.days + day
        s.copy(days = days)
    }

    fun setFrequency(count: Int) = update { it.copy(days = OnboardingUiState.suggestDays(count.coerceIn(1, 7))) }

    private fun answers(s: OnboardingUiState): OnboardingAnswers? {
        val profile = s.equipment.toProfile(id = "home", name = "Home") ?: return null
        return OnboardingAnswers(
            name = s.name,
            goal = s.goal ?: Goal.GENERAL_FITNESS,
            experience = s.experience ?: ExperienceLevel.NEW,
            equipment = profile,
            sessionMinutes = s.minutes,
            days = s.days,
            quiet = s.quiet,
            limitedSpace = s.limitedSpace,
        )
    }

    private fun buildPreview() = launch {
        update { it.copy(preview = null, previewError = null) }
        val answers = answers(current)
        val generated = answers?.let { services.onboarding.previewFirstWorkout(it) }
        if (generated == null) {
            update { it.copy(previewError = "We couldn't build a workout from these answers. Check your equipment and try again.") }
        } else {
            update { it.copy(preview = PlanMapper.toUi(generated, services.catalog, "program")) }
        }
    }

    /** Saves the answers and goes to Today. [startNow] opens the workout preview instead. */
    fun finish(startNow: Boolean) {
        val s = current
        if (s.finishing) return
        val answers = answers(s) ?: return
        update { it.copy(finishing = true) }
        launch {
            services.onboarding.complete(answers)
            services.reminders.update(services.repos.userState.current().settings.reminders, services.repos.userState.current().schedule)
            navigate(Destination.Main(Tab.TODAY), clear = true)
            if (startNow) navigate(Destination.Preview("program"))
        }
    }
}
